### ISSUE TITLE
reddit.com is blocked

### ISSUE THREAD

**Issue by ite-usagi** [NotaInutilis/Super-SEO-Spam-Suppressor#1]
The latest commit blocks reddit.com, is this intentional? I think this is probably caused by importing [my list](https://github.com/ite-usagi/ublacklist-noai). My list blocks some subreddits within reddit.com, but it looks like this commit incorrectly blocks all directories.

**Comment by NotaInutilis** [comment]
Yep, my import code is pretty terrible in general, and particularly awful at dealing with anything that's not a domain. Thanks for the heads up, I'll put reddit in the allowlist.
