### ISSUE TITLE
FALSE POSTIVE - chatgpt.com  www.chatgpt.com

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [NotaInutilis/Super-SEO-Spam-Suppressor#12]

**Comment by NotaInutilis** [comment]
That's not a false positive, you should add it to your own allowlist if you need to use it.

**Comment by RubenKelevra** [comment]
It's definitly not fitting the description of this blocklist:

"An anticapitalist blocklist targeting websites abusing SEO tactics to spam web searches with data pollution and security risks"

How is chatgpt abusing SEO tactics?
