### ISSUE TITLE
 *://*.xda-developers.com/* is legit

### ISSUE THREAD

**Issue by mid-kid** [NotaInutilis/Super-SEO-Spam-Suppressor#15]
xda-developers not only is a reputable news source for smart phone and smart phone hacking, but also a forum containing a lot of useful information and discussion about smartphones.
I can't find out why it ended up on this list.

**Comment by NotaInutilis** [comment]
This addition was indeed sad. The site xda dev has been acquired by valnet in 2022 and is only publishing useless seo trash at this point. The forum uses a different domain and isn't blocked, as I agree that it's a very valuable ressource.
