### ISSUE TITLE
Blocking *.waw.pl is overbroad

### ISSUE THREAD

**Issue by fbrzoz** [NotaInutilis/Super-SEO-Spam-Suppressor#17]
Hi, first of all - thank you for making this list! I really have a hard time understating how much cleaner it made my browsing experience lately.

Yesterday, I noticed that the list includes everything under `*.waw.pl`, which while it might block *some* garbage, it also inevitably includes false positives, as it's [a legitimate second-level domain](https://www.dns.pl/en/list_of_regional_domain_names) in Poland. This, in turn, leads to legitimate sites being blocked, like [the local transport authority](https://wtp.waw.pl), or [the Academy of Fine Arts](https://en.asp.waw.pl). I'd like to recommend deleting that filter and replacing it with something more specific, if possible.

**Comment by NotaInutilis** [comment]
Hey, glad you find this list useful!

I've fixed the false positive, it comes from one of the many lists that I've aggregated here (the Search Engine Spam Blocklist, which has unfortunately been archived). It's an impossible task to parse all these entries by myself, especially for countries and cultures I know nothing about, so thanks for your help in fixing those issues!
